import { PlanLimits, PlanTier } from '../types/license';
import { TemplateConfig } from '../types/template';

export const APP_NAME = 'MINGLEBOOTH';
export const GALLERY_RETENTION_DAYS = 30;

export const DEFAULT_PLAN_LIMITS: Record<PlanTier, PlanLimits> = {
  starter: {
    tier: 'starter',
    maxDevices: 1,
    unlimitedEvents: true,
    unlimitedTemplates: false,
    gifSupport: 'basic',
    customBranding: false,
    whiteLabel: false,
    customDomain: false,
    multiUser: false,
    apiAccess: false,
    galleryRetentionDays: GALLERY_RETENTION_DAYS,
  },
  pro: {
    tier: 'pro',
    maxDevices: 3,
    unlimitedEvents: true,
    unlimitedTemplates: true,
    gifSupport: 'advanced',
    customBranding: true,
    whiteLabel: false,
    customDomain: false,
    multiUser: true,
    apiAccess: false,
    galleryRetentionDays: GALLERY_RETENTION_DAYS,
  },
  business: {
    tier: 'business',
    maxDevices: 10,
    unlimitedEvents: true,
    unlimitedTemplates: true,
    gifSupport: 'advanced',
    customBranding: true,
    whiteLabel: true,
    customDomain: true,
    multiUser: true,
    apiAccess: true,
    galleryRetentionDays: GALLERY_RETENTION_DAYS,
  },
  enterprise: {
    tier: 'enterprise',
    maxDevices: 999,
    unlimitedEvents: true,
    unlimitedTemplates: true,
    gifSupport: 'advanced',
    customBranding: true,
    whiteLabel: true,
    customDomain: true,
    multiUser: true,
    apiAccess: true,
    galleryRetentionDays: GALLERY_RETENTION_DAYS,
  },
};

export const DEFAULT_PORTRAIT_TEMPLATE: TemplateConfig = {
  id: 'tpl_default_portrait',
  name: 'Standard Portrait (4x5)',
  description: 'Clean single shot portrait format for social and print',
  aspectRatio: '4:5',
  canvas: {
    width: 1080,
    height: 1350,
  },
  photoSlots: [
    {
      id: 'slot_1',
      x: 40,
      y: 40,
      width: 1000,
      height: 1160,
      fit: 'cover',
      borderRadius: 16,
    },
  ],
  texts: [
    {
      id: 'txt_event',
      text: 'MingleBooth Live Event',
      x: 540,
      y: 1250,
      fontSize: 32,
      fontFamily: 'Inter, sans-serif',
      fontWeight: 'bold',
      color: '#FFFFFF',
      textAlign: 'center',
    },
    {
      id: 'txt_date',
      text: 'Capture The Moment',
      x: 540,
      y: 1300,
      fontSize: 20,
      fontFamily: 'Inter, sans-serif',
      fontWeight: 'normal',
      color: '#9CA3AF',
      textAlign: 'center',
    },
  ],
  background: {
    type: 'color',
    color: '#090D16',
  },
  dpi: 300,
  isDefault: true,
};

export const DEFAULT_STRIP_TEMPLATE: TemplateConfig = {
  id: 'tpl_default_strip',
  name: 'Classic 3-Photo Strip (2x6)',
  description: 'Classic vertical 3-shot photobooth strip',
  aspectRatio: '2:6',
  canvas: {
    width: 600,
    height: 1800,
  },
  photoSlots: [
    {
      id: 'slot_1',
      x: 40,
      y: 40,
      width: 520,
      height: 480,
      fit: 'cover',
      borderRadius: 8,
    },
    {
      id: 'slot_2',
      x: 40,
      y: 560,
      width: 520,
      height: 480,
      fit: 'cover',
      borderRadius: 8,
    },
    {
      id: 'slot_3',
      x: 40,
      y: 1080,
      width: 520,
      height: 480,
      fit: 'cover',
      borderRadius: 8,
    },
  ],
  texts: [
    {
      id: 'txt_event',
      text: 'MINGLEBOOTH',
      x: 300,
      y: 1660,
      fontSize: 28,
      fontFamily: 'Inter, sans-serif',
      fontWeight: 'bold',
      color: '#FFFFFF',
      textAlign: 'center',
    },
    {
      id: 'txt_footer',
      text: 'www.minglebooth.com',
      x: 300,
      y: 1720,
      fontSize: 16,
      fontFamily: 'Inter, sans-serif',
      fontWeight: 'normal',
      color: '#9CA3AF',
      textAlign: 'center',
    },
  ],
  background: {
    type: 'color',
    color: '#0F172A',
  },
  dpi: 300,
};
